[package]
name = "litopts_mac"
version = "0.1.0"
authors = [ "mahkoh" ]

[[lib]]
name = "litopts_mac"
path = "src/litopts_mac.rs"
crate-types = ["dylib"]

[dependencies.litopts]
git = "https://github.com/mahkoh/litopts.git"
